#!/bin/bash

echo "Dental SaaS Database Setup Instructions"
echo "======================================="
echo ""
echo "Since this is a new project, you need to apply the database schema to your Supabase project."
echo ""
echo "1. Go to your Supabase Dashboard: https://supabase.com/dashboard"
echo "2. Select your project (e.g., 'focus-supabase-cyan-park')"
echo "3. Go to the SQL Editor (icon on the left sidebar)"
echo "4. Click 'New Query'"
echo "5. Copy the content of 'supabase/migrations/20260214000000_initial_schema.sql'"
echo "6. Paste it into the SQL Editor and click 'Run'"
echo "7. Repeat steps 4-6 for 'supabase/migrations/20260214000001_rls_policies.sql'"
echo ""
echo "Once done, your database will be ready with:"
echo "- Multi-tenant tables (clinics, users, patients, etc.)"
echo "- Row Level Security (RLS) policies"
echo "- Storage buckets"
echo ""
echo "You can finding the migration files in the 'supabase/migrations' folder."
